[2025-10-26T17:10:02.077+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-26T17:10:02.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T17:05:00+00:00 [queued]>
[2025-10-26T17:10:02.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T17:05:00+00:00 [queued]>
[2025-10-26T17:10:02.123+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-26T17:10:02.142+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-26 17:05:00+00:00
[2025-10-26T17:10:02.152+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-26T17:05:00+00:00', '--job-id', '880', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpm7ud1lj7']
[2025-10-26T17:10:02.153+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-26T17:10:02.154+0000] {standard_task_runner.py:91} INFO - Job 880: Subtask fetch_weather_data
[2025-10-26T17:10:02.155+0000] {standard_task_runner.py:63} INFO - Started process 322 to run task
[2025-10-26T17:10:02.213+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T17:05:00+00:00 [running]> on host ac7c4fe30011
[2025-10-26T17:10:02.313+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-26T17:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-26T17:05:00+00:00'
[2025-10-26T17:10:02.316+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-26T17:10:02.372+0000] {logging_mixin.py:188} INFO - âœ… Weather fetched. Rain (1h/24h): 0.00 / 0.00. Humidity: 77.4
[2025-10-26T17:10:02.373+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 21.74, 'humidity': 77.42, 'pressure': 1021.51, 'wind_speed': 13.18, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 17, 'day': 26, 'month': 10, 'year': 2025}
[2025-10-26T17:10:02.374+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-26T17:10:02.397+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-26T17:05:00+00:00, execution_date=20251026T170500, start_date=20251026T171002, end_date=20251026T171002
[2025-10-26T17:10:02.450+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-26T17:10:02.477+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-26T17:10:02.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
