[2025-10-30T17:15:02.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T17:15:02.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-30T17:10:00+00:00 [queued]>
[2025-10-30T17:15:02.188+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-30T17:10:00+00:00 [queued]>
[2025-10-30T17:15:02.189+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T17:15:02.204+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-30 17:10:00+00:00
[2025-10-30T17:15:02.215+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1701) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T17:15:02.214+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-30T17:10:00+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpljnp4cvd']
[2025-10-30T17:15:02.217+0000] {standard_task_runner.py:63} INFO - Started process 1704 to run task
[2025-10-30T17:15:02.217+0000] {standard_task_runner.py:91} INFO - Job 240: Subtask fetch_weather_data
[2025-10-30T17:15:02.276+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-30T17:10:00+00:00 [running]> on host ed0a55a1b19d
[2025-10-30T17:15:02.363+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T17:10:00+00:00'
[2025-10-30T17:15:02.365+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T17:15:02.431+0000] {logging_mixin.py:188} INFO - âœ… Weather fetched. Rain (1h/24h): 0.0 / 0.0
[2025-10-30T17:15:02.432+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 34.24, 'humidity': 75.65, 'pressure': 1003.47, 'wind_speed': 1.51, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 1.9699999999999989, 'humidity_delta': 5.550000000000011, 'hour': 17, 'day': 30, 'month': 10, 'year': 2025}
[2025-10-30T17:15:02.433+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T17:15:02.451+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-30T17:10:00+00:00, execution_date=20251030T171000, start_date=20251030T171502, end_date=20251030T171502
[2025-10-30T17:15:02.472+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T17:15:02.491+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T17:15:02.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
