[2025-10-21T14:50:01.480+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T14:50:01.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T14:45:00+00:00 [queued]>
[2025-10-21T14:50:01.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T14:45:00+00:00 [queued]>
[2025-10-21T14:50:01.509+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-21T14:50:01.522+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-21 14:45:00+00:00
[2025-10-21T14:50:01.530+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=613) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-21T14:50:01.530+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-21T14:45:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpxzmumto_']
[2025-10-21T14:50:01.531+0000] {standard_task_runner.py:63} INFO - Started process 616 to run task
[2025-10-21T14:50:01.532+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask fetch_weather_data
[2025-10-21T14:50:01.573+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T14:45:00+00:00 [running]> on host e4cb5f9e7d00
[2025-10-21T14:50:01.647+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-21T14:45:00+00:00'
[2025-10-21T14:50:01.649+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T14:50:01.691+0000] {logging_mixin.py:188} INFO - âœ… Weather data fetched: {'temp': 27.45, 'humidity': 85.96, 'pressure': 1032.9, 'wind_speed': 1.05, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 14, 'day': 21, 'month': 10, 'year': 2025}
[2025-10-21T14:50:01.692+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 27.45, 'humidity': 85.96, 'pressure': 1032.9, 'wind_speed': 1.05, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 14, 'day': 21, 'month': 10, 'year': 2025}
[2025-10-21T14:50:01.693+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T14:50:01.716+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-21T14:45:00+00:00, execution_date=20251021T144500, start_date=20251021T145001, end_date=20251021T145001
[2025-10-21T14:50:01.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-21T14:50:01.796+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-21T14:50:01.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
