[2025-10-29T16:20:07.344+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-29T16:20:07.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.send_slack_alert scheduled__2025-10-29T16:15:00+00:00 [queued]>
[2025-10-29T16:20:07.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.send_slack_alert scheduled__2025-10-29T16:15:00+00:00 [queued]>
[2025-10-29T16:20:07.371+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-29T16:20:07.382+0000] {taskinstance.py:2330} INFO - Executing <Task(SlackWebhookOperator): send_slack_alert> on 2025-10-29 16:15:00+00:00
[2025-10-29T16:20:07.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'send_slack_alert', 'scheduled__2025-10-29T16:15:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp1lvx5s5f']
[2025-10-29T16:20:07.389+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4432) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-29T16:20:07.390+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask send_slack_alert
[2025-10-29T16:20:07.390+0000] {standard_task_runner.py:63} INFO - Started process 4435 to run task
[2025-10-29T16:20:07.427+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.send_slack_alert scheduled__2025-10-29T16:15:00+00:00 [running]> on host db3c1202c602
[2025-10-29T16:20:07.502+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='send_slack_alert' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T16:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T16:15:00+00:00'
[2025-10-29T16:20:07.503+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-29T16:20:07.525+0000] {base.py:84} INFO - Using connection ID 'slack_webhook_default' for task execution.
[2025-10-29T16:20:08.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-29T16:20:08.067+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=send_slack_alert, run_id=scheduled__2025-10-29T16:15:00+00:00, execution_date=20251029T161500, start_date=20251029T162007, end_date=20251029T162008
[2025-10-29T16:20:08.087+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-29T16:20:08.100+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-29T16:20:08.104+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
