[2025-10-18T18:30:01.228+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T18:30:01.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-18T18:25:00+00:00 [queued]>
[2025-10-18T18:30:01.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-18T18:25:00+00:00 [queued]>
[2025-10-18T18:30:01.254+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-18T18:30:01.265+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-18 18:25:00+00:00
[2025-10-18T18:30:01.272+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-18T18:30:01.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-18T18:25:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmprw7gbvel']
[2025-10-18T18:30:01.273+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2025-10-18T18:30:01.274+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask fetch_weather_data
[2025-10-18T18:30:01.314+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-18T18:25:00+00:00 [running]> on host fcca755cbcb6
[2025-10-18T18:30:01.379+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T18:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-18T18:25:00+00:00'
[2025-10-18T18:30:01.380+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T18:30:01.415+0000] {logging_mixin.py:188} INFO - âœ… Weather data fetched: {'temp': 34.5210173431181, 'humidity': 68.99418052302673, 'pressure': 1024.1213150254882, 'wind_speed': 11.292469044168556, 'rain_1h': 4.911549393462495, 'rain_3h': 43.75715489241243, 'rain_6h': 103.4951396568946, 'rain_24h': 232.25002529969896, 'rain_intensity': 9.190913126256566, 'temp_delta': 3.9590271683551705, 'humidity_delta': 8.42102696558203, 'year': 2025, 'month': 10, 'day': 18, 'hour': 18, 'minute': 30, 'second': 1}
[2025-10-18T18:30:01.416+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 34.5210173431181, 'humidity': 68.99418052302673, 'pressure': 1024.1213150254882, 'wind_speed': 11.292469044168556, 'rain_1h': 4.911549393462495, 'rain_3h': 43.75715489241243, 'rain_6h': 103.4951396568946, 'rain_24h': 232.25002529969896, 'rain_intensity': 9.190913126256566, 'temp_delta': 3.9590271683551705, 'humidity_delta': 8.42102696558203, 'year': 2025, 'month': 10, 'day': 18, 'hour': 18, 'minute': 30, 'second': 1}
[2025-10-18T18:30:01.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T18:30:01.434+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-18T18:25:00+00:00, execution_date=20251018T182500, start_date=20251018T183001, end_date=20251018T183001
[2025-10-18T18:30:01.448+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-18T18:30:01.461+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-18T18:30:01.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
