[2025-10-21T15:25:01.962+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T15:25:01.982+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T15:20:00+00:00 [queued]>
[2025-10-21T15:25:01.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T15:20:00+00:00 [queued]>
[2025-10-21T15:25:01.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-21T15:25:02.004+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-21 15:20:00+00:00
[2025-10-21T15:25:02.012+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1200) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-21T15:25:02.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-21T15:20:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpn129rn9t']
[2025-10-21T15:25:02.014+0000] {standard_task_runner.py:63} INFO - Started process 1203 to run task
[2025-10-21T15:25:02.014+0000] {standard_task_runner.py:91} INFO - Job 279: Subtask fetch_weather_data
[2025-10-21T15:25:02.058+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-21T15:20:00+00:00 [running]> on host e4cb5f9e7d00
[2025-10-21T15:25:02.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T15:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-21T15:20:00+00:00'
[2025-10-21T15:25:02.137+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T15:25:02.175+0000] {logging_mixin.py:188} INFO - âœ… Weather data fetched: {'temp': 27.45, 'humidity': 85.96, 'pressure': 1032.9, 'wind_speed': 1.05, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 15, 'day': 21, 'month': 10, 'year': 2025}
[2025-10-21T15:25:02.177+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 27.45, 'humidity': 85.96, 'pressure': 1032.9, 'wind_speed': 1.05, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 15, 'day': 21, 'month': 10, 'year': 2025}
[2025-10-21T15:25:02.177+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T15:25:02.194+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-21T15:20:00+00:00, execution_date=20251021T152000, start_date=20251021T152501, end_date=20251021T152502
[2025-10-21T15:25:02.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-21T15:25:02.246+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-21T15:25:02.251+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
