[2025-10-30T17:44:34.012+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T17:44:34.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data manual__2025-10-30T17:44:32.349319+00:00 [queued]>
[2025-10-30T17:44:34.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data manual__2025-10-30T17:44:32.349319+00:00 [queued]>
[2025-10-30T17:44:34.046+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T17:44:34.062+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-30 17:44:32.349319+00:00
[2025-10-30T17:44:34.070+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1525) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T17:44:34.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'manual__2025-10-30T17:44:32.349319+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpxjiw0tab']
[2025-10-30T17:44:34.071+0000] {standard_task_runner.py:63} INFO - Started process 1528 to run task
[2025-10-30T17:44:34.072+0000] {standard_task_runner.py:91} INFO - Job 276: Subtask fetch_weather_data
[2025-10-30T17:44:34.124+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data manual__2025-10-30T17:44:32.349319+00:00 [running]> on host adac321c4d0a
[2025-10-30T17:44:34.208+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T17:44:32.349319+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T17:44:32.349319+00:00'
[2025-10-30T17:44:34.210+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T17:44:34.286+0000] {logging_mixin.py:188} INFO - âœ… Weather fetched. Rain (1h/24h): 0.0 / 0.0
[2025-10-30T17:44:34.288+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 20.29, 'humidity': 80.28, 'pressure': 1000.89, 'wind_speed': 17.89, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': -11.980000000000004, 'humidity_delta': 10.180000000000007, 'hour': 17, 'day': 30, 'month': 10, 'year': 2025}
[2025-10-30T17:44:34.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T17:44:34.313+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=manual__2025-10-30T17:44:32.349319+00:00, execution_date=20251030T174432, start_date=20251030T174434, end_date=20251030T174434
[2025-10-30T17:44:34.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T17:44:34.400+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T17:44:34.404+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
