[2025-10-29T15:10:05.627+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-29T15:10:05.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-29T15:05:00+00:00 [queued]>
[2025-10-29T15:10:05.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-29T15:05:00+00:00 [queued]>
[2025-10-29T15:10:05.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-29T15:10:05.868+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-29 15:05:00+00:00
[2025-10-29T15:10:05.942+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-29T15:05:00+00:00', '--job-id', '424', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpv2kz4jua']
[2025-10-29T15:10:05.950+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3973) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-29T15:10:05.956+0000] {standard_task_runner.py:91} INFO - Job 424: Subtask fetch_weather_data
[2025-10-29T15:10:05.957+0000] {standard_task_runner.py:63} INFO - Started process 3989 to run task
[2025-10-29T15:10:06.415+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-29T15:05:00+00:00 [running]> on host 31e670d1ab03
[2025-10-29T15:10:06.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T15:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T15:05:00+00:00'
[2025-10-29T15:10:06.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-29T15:10:07.187+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/flood_prediction_dag.py:133 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2025-10-29T15:10:07.222+0000] {logging_mixin.py:188} INFO - âœ… Weather fetched. Rain (1h/24h): 0.00 / 0.00. Humidity: 79.3
[2025-10-29T15:10:07.224+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 30.61, 'humidity': 79.33, 'pressure': 992.57, 'wind_speed': 2.74, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 15, 'day': 29, 'month': 10, 'year': 2025}
[2025-10-29T15:10:07.226+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-29T15:10:07.341+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-29T15:05:00+00:00, execution_date=20251029T150500, start_date=20251029T151005, end_date=20251029T151007
[2025-10-29T15:10:07.432+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-29T15:10:07.529+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-29T15:10:07.538+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
