[2025-10-26T18:05:01.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-26T18:05:01.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T18:00:00+00:00 [queued]>
[2025-10-26T18:05:01.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T18:00:00+00:00 [queued]>
[2025-10-26T18:05:01.199+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-26T18:05:01.210+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2025-10-26 18:00:00+00:00
[2025-10-26T18:05:01.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'fetch_weather_data', 'scheduled__2025-10-26T18:00:00+00:00', '--job-id', '937', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpvkanltvb']
[2025-10-26T18:05:01.218+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=359) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-26T18:05:01.219+0000] {standard_task_runner.py:91} INFO - Job 937: Subtask fetch_weather_data
[2025-10-26T18:05:01.220+0000] {standard_task_runner.py:63} INFO - Started process 362 to run task
[2025-10-26T18:05:01.263+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.fetch_weather_data scheduled__2025-10-26T18:00:00+00:00 [running]> on host dcca0869200f
[2025-10-26T18:05:01.333+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-26T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-26T18:00:00+00:00'
[2025-10-26T18:05:01.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-26T18:05:01.394+0000] {logging_mixin.py:188} INFO - âœ… Weather fetched. Rain (1h/24h): 0.00 / 0.00. Humidity: 84.5
[2025-10-26T18:05:01.395+0000] {python.py:237} INFO - Done. Returned value was: {'temp': 21.37, 'humidity': 84.5, 'pressure': 1005.25, 'wind_speed': 13.83, 'rain_1h': 0.0, 'rain_3h': 0.0, 'rain_6h': 0.0, 'rain_24h': 0.0, 'rain_intensity': 0.0, 'temp_delta': 0.0, 'humidity_delta': 0.0, 'hour': 18, 'day': 26, 'month': 10, 'year': 2025}
[2025-10-26T18:05:01.396+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-26T18:05:01.415+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=fetch_weather_data, run_id=scheduled__2025-10-26T18:00:00+00:00, execution_date=20251026T180000, start_date=20251026T180501, end_date=20251026T180501
[2025-10-26T18:05:01.435+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-26T18:05:01.453+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-26T18:05:01.456+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
